In [8]:
import pandas as pd
df = pd.read_csv('data/gapminder.tsv', sep='\t')
print(df.head())

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [9]:
avg_life_exp_by_year = df.groupby('year')['lifeExp'].mean()
print(avg_life_exp_by_year)

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [10]:
manual_life_exp_grouped = pd.DataFrame(columns=['year', 'avg_life'])
years = df['year'].unique()
print(years)

for year in years:
    mean = df[df['year'] == year]['lifeExp'].mean()
    manual_life_exp_grouped.loc[len(manual_life_exp_grouped), :] = {'year': year, 'avg_life': mean}

print(manual_life_exp_grouped.head(10))

[1952 1957 1962 1967 1972 1977 1982 1987 1992 1997 2002 2007]
     year   avg_life
0  1952.0   49.05762
1  1957.0  51.507401
2  1962.0  53.609249
3  1967.0   55.67829
4  1972.0  57.647386
5  1977.0  59.570157
6  1982.0  61.533197
7  1987.0  63.212613
8  1992.0  64.160338
9  1997.0  65.014676

In [11]:
def my_mean(values):
    n = len(values)
    sum = 0
    for value in values:
        sum += value
    return sum / n

agg_my_mean = df.groupby('year').lifeExp.agg(my_mean)
print(agg_my_mean)

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [12]:
def my_mean_diff(values, diff_value):
    return my_mean(values) - diff_value

global_mean = df.lifeExp.mean()
print(global_mean)

agg_mean_diff = df.groupby('year').lifeExp.agg(my_mean_diff, global_mean)
print(agg_mean_diff)

59.474439366197174
year
1952   -10.416820
1957    -7.967038
1962    -5.865190
1967    -3.796150
1972    -1.827053
1977     0.095718
1982     2.058758
1987     3.738173
1992     4.685899
1997     5.540237
2002     6.220483
2007     7.532983
Name: lifeExp, dtype: float64

In [13]:
import numpy as np
gdf = df.groupby('year').lifeExp.agg([np.count_nonzero, np.mean, np.std])
print(gdf)

      count_nonzero       mean        std
year
1952            142  49.057620  12.225956
1957            142  51.507401  12.231286
1962            142  53.609249  12.097245
1967            142  55.678290  11.718858
1972            142  57.647386  11.381953
1977            142  59.570157  11.227229
1982            142  61.533197  10.770618
1987            142  63.212613  10.556285
1992            142  64.160338  11.227380
1997            142  65.014676  11.559439
2002            142  65.694923  12.279823
2007            142  67.007423  12.073021

C:\Users\taehy\AppData\Local\Temp\ipykernel_24088\182961998.py:2: FutureWarning: The provided callable <function mean at 0x000002515C0EBA60> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  gdf = df.groupby('year').lifeExp.agg([np.count_nonzero, np.mean, np.std])
C:\Users\taehy\AppData\Local\Temp\ipykernel_24088\182961998.py:2: FutureWarning: The provided callable <function std at 0x000002515C0EBBA0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  gdf = df.groupby('year').lifeExp.agg([np.count_nonzero, np.mean, np.std])

In [17]:
df = pd.DataFrame({
    'dept': ['A', 'B', 'B', 'A', 'A'],
    'salary' : [100, 200, 300, 400, 500]
})
df.head()

  dept  salary
0    A     100
1    B     200
2    B     300
3    A     400
4    A     500

In [19]:
def mean(values):
    sum = 0
    for value in values:
        sum += value
    return sum / len(values)

df.groupby('dept')['salary'].agg(mean)

dept
A    333.333333
B    250.000000
Name: salary, dtype: float64

In [ ]:
def plus_value(x, value):
    return x + value

df['adjusted'] = df.groupby('dept')['salary'].transform(plus_value, 100)
df.head()

# A 그룹
# salary = [100, 200]

# plus_value([100, 200], 100)
# → [200, 300]

# B 그룹
# salary = [300, 400, 500]

# plus_value([300, 400, 500], 100)
# → [400, 500, 600]

  dept  salary  adjusted
0    A     100       200
1    B     200       300
2    B     300       400
3    A     400       500
4    A     500       600

In [33]:
result1 = df.groupby('dept')['salary'].apply(plus_value, 100)
print(result1)

result2 = df.groupby('dept')['salary'].transform(plus_value, 100)
print(result2)

dept
A     0    200
      3    500
      4    600
B     1    300
      2    400
Name: salary, dtype: int64
0    200
1    300
2    400
3    500
4    600
Name: salary, dtype: int64

In [34]:
df = pd.DataFrame({
    'dept': ['A', 'A', 'A', 'B', 'B', 'B'],
    'name': ['Kim', 'Lee', 'Park', 'Choi', 'Jung', 'Han'],
    'salary': [300, 500, 400, 700, 600, 800]
})

df.head()

  dept  name  salary
0    A   Kim     300
1    A   Lee     500
2    A  Park     400
3    B  Choi     700
4    B  Jung     600

In [43]:
test = pd.Series([1, 2, 3, 4, 5, 100])
test.name = 'salary'
test_result = test.nlargest(2)
print(test_result)

result = df.groupby('dept').apply(
    lambda x: x.nlargest(2, 'salary')
)
print(result)

5    100
4      5
Name: salary, dtype: int64
       dept  name  salary
dept
A    1    A   Lee     500
     2    A  Park     400
B    5    B   Han     800
     3    B  Choi     700

C:\Users\taehy\AppData\Local\Temp\ipykernel_24088\6012104.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('dept').apply(

In [44]:
import pandas as pd

df = pd.DataFrame({
    'dept': ['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C'],
    'name': ['Kim', 'Lee', 'Park', 'Choi', 'Jung', 'Han', 'Yoon', 'Kang'],
    'salary': [300, 500, 400, 700, 600, 800, 450, 550],
    'experience': [2, 5, 3, 7, 6, 8, 4, 6]
})

print(df)

  dept  name  salary  experience
0    A   Kim     300           2
1    A   Lee     500           5
2    A  Park     400           3
3    B  Choi     700           7
4    B  Jung     600           6
5    B   Han     800           8
6    C  Yoon     450           4
7    C  Kang     550           6

In [51]:
print(df.groupby('dept')['salary'].agg(['mean','max','min']))
print(df.groupby('dept')['experience'].agg('mean'))


df['avg_sal'] = df.groupby('dept')['salary'].transform(mean)
print(df)

result = df.groupby('dept').apply(lambda x:x.nlargest(2, 'salary'))
print(result)

       mean  max  min
dept
A     400.0  500  300
B     700.0  800  600
C     500.0  550  450
dept
A    3.333333
B    7.000000
C    5.000000
Name: experience, dtype: float64
  dept  name  salary  experience  avg_sal
0    A   Kim     300           2    400.0
1    A   Lee     500           5    400.0
2    A  Park     400           3    400.0
3    B  Choi     700           7    700.0
4    B  Jung     600           6    700.0
5    B   Han     800           8    700.0
6    C  Yoon     450           4    500.0
7    C  Kang     550           6    500.0
       dept  name  salary  experience  avg_sal
dept
A    1    A   Lee     500           5    400.0
     2    A  Park     400           3    400.0
B    5    B   Han     800           8    700.0
     3    B  Choi     700           7    700.0
C    7    C  Kang     550           6    500.0
     6    C  Yoon     450           4    500.0

C:\Users\taehy\AppData\Local\Temp\ipykernel_24088\2237342284.py:8: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('dept').apply(lambda x:x.nlargest(2, 'salary'))

In [59]:
import pandas as pd 
df = pd.read_csv('data/gapminder.tsv', sep='\t')
print(df.head())
print(df.count())

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
country      1704
continent    1704
year         1704
lifeExp      1704
pop          1704
gdpPercap    1704
dtype: int64

In [60]:
def my_zscore(x):
    return (x - x.mean()) / x.std()

transform_z = df.groupby('year').lifeExp.transform(my_zscore)
print(transform_z.head())
print(transform_z.count())

df['transform_z'] = transform_z
print(df.head())

0   -1.656854
1   -1.731249
2   -1.786543
3   -1.848157
4   -1.894173
Name: lifeExp, dtype: float64
1704
       country continent  year  lifeExp       pop   gdpPercap  transform_z
0  Afghanistan      Asia  1952   28.801   8425333  779.445314    -1.656854
1  Afghanistan      Asia  1957   30.332   9240934  820.853030    -1.731249
2  Afghanistan      Asia  1962   31.997  10267083  853.100710    -1.786543
3  Afghanistan      Asia  1967   34.020  11537966  836.197138    -1.848157
4  Afghanistan      Asia  1972   36.088  13079460  739.981106    -1.894173

In [82]:
import seaborn as sns
import numpy as np
np.random.seed(42)


tips_10 = sns.load_dataset('tips').sample(10)
tips_10.loc[np.random.permutation(tips_10.index)[:4], 'total_bill'] = np.nan

print(tips_10)
result = tips_10['total_bill'].isna()
print(result)
print(tips_10[result])
print(tips_10.loc[result])

     total_bill   tip     sex smoker   day    time  size
24        19.82  3.18    Male     No   Sat  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
153         NaN  2.00    Male     No   Sun  Dinner     4
211         NaN  5.16    Male    Yes   Sat  Dinner     4
198         NaN  2.00  Female    Yes  Thur   Lunch     2
176         NaN  2.00    Male    Yes   Sun  Dinner     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
9         14.78  3.23    Male     No   Sun  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
24     False
6      False
153     True
211     True
198     True
176     True
192    False
124    False
9      False
101    False
Name: total_bill, dtype: bool
     total_bill   tip     sex smoker   day    time  size
153         NaN  2.00    Male     No   Sun  Dinner     4
211         NaN  5.16    Male    Yes   Sat  Dinner     4
198         NaN  2.00  Female    Yes  Thur   Lunch     2
176         NaN  2.00    Male    Yes   Sun  Dinner     2
     total_bill   tip     sex smoker   day    time  size
153         NaN  2.00    Male     No   Sun  Dinner     4
211         NaN  5.16    Male    Yes   Sat  Dinner     4
198         NaN  2.00  Female    Yes  Thur   Lunch     2
176         NaN  2.00    Male    Yes   Sun  Dinner     2

In [87]:
print(tips_10.groupby('sex').count())
print(tips_10.groupby('sex')['total_bill'].mean())

        total_bill  tip  smoker  day  time  size
sex
Male             4    7       7    7     7     7
Female           2    3       3    3     3     3
sex
Male      17.9525
Female    13.9300
Name: total_bill, dtype: float64

C:\Users\taehy\AppData\Local\Temp\ipykernel_24088\2217251090.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(tips_10.groupby('sex').count())
C:\Users\taehy\AppData\Local\Temp\ipykernel_24088\2217251090.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(tips_10.groupby('sex')['total_bill'].mean())

In [90]:
def fill_na_mean(x):
    avg = x.mean()
    return x.fillna(avg)

total_bill_group_mean = tips_10.groupby('sex').total_bill.transform(fill_na_mean)
print(total_bill_group_mean)
tips_10['fill_total_bill'] = total_bill_group_mean
print(tips_10)

24     19.8200
6       8.7700
153    17.9525
211    17.9525
198    13.9300
176    17.9525
192    28.4400
124    12.4800
9      14.7800
101    15.3800
Name: total_bill, dtype: float64
     total_bill   tip     sex smoker   day    time  size  fill_total_bill
24        19.82  3.18    Male     No   Sat  Dinner     2          19.8200
6          8.77  2.00    Male     No   Sun  Dinner     2           8.7700
153         NaN  2.00    Male     No   Sun  Dinner     4          17.9525
211         NaN  5.16    Male    Yes   Sat  Dinner     4          17.9525
198         NaN  2.00  Female    Yes  Thur   Lunch     2          13.9300
176         NaN  2.00    Male    Yes   Sun  Dinner     2          17.9525
192       28.44  2.56    Male    Yes  Thur   Lunch     2          28.4400
124       12.48  2.52  Female     No  Thur   Lunch     2          12.4800
9         14.78  3.23    Male     No   Sun  Dinner     2          14.7800
101       15.38  3.00  Female    Yes   Fri  Dinner     2          15.3800

C:\Users\taehy\AppData\Local\Temp\ipykernel_24088\2453639830.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  total_bill_group_mean = tips_10.groupby('sex').total_bill.transform(fill_na_mean)

In [99]:
df = pd.DataFrame({
    'dept' : ['A', 'A', 'B'],
    'salary' : [200, 300, 400],
    'experience' : [3, 4, 5]
})
print(df)
df.groupby('dept').filter(lambda x: x['salary'].mean() > 250)

  dept  salary  experience
0    A     200           3
1    A     300           4
2    B     400           5

  dept  salary  experience
2    B     400           5

In [100]:
tips = sns.load_dataset('tips')
print(tips.shape)

(244, 7)

In [101]:
print(tips['size'].value_counts())

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [108]:
tips_filtered = tips.groupby('size').filter(lambda x: x['sex'].count() >= 30)
tips_2 = tips.groupby('size').get_group(2)
print(tips_2)
print(tips_2.count())
print(tips_filtered['size'].value_counts())

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
3         23.68  3.31    Male     No   Sun  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
237       32.83  1.17    Male    Yes   Sat  Dinner     2
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[156 rows x 7 columns]
total_bill    156
tip           156
sex           156
smoker        156
day           156
time          156
size          156
dtype: int64
size
2    156
3     38
4     37
Name: count, dtype: int64

In [109]:
tips_10 = sns.load_dataset('tips').sample(10, random_state=42)
print(tips_10)

     total_bill   tip     sex smoker   day    time  size
24        19.82  3.18    Male     No   Sat  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
153       24.55  2.00    Male     No   Sun  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
198       13.00  2.00  Female    Yes  Thur   Lunch     2
176       17.89  2.00    Male    Yes   Sun  Dinner     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
9         14.78  3.23    Male     No   Sun  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2

In [111]:
grouped = tips_10.groupby('sex')
print(grouped)
print(grouped.groups)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002517EA1E200>
{'Male': [24, 6, 153, 211, 176, 192, 9], 'Female': [198, 124, 101]}

C:\Users\taehy\AppData\Local\Temp\ipykernel_24088\2414312736.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = tips_10.groupby('sex')

In [113]:
female = grouped.get_group('Female')
print(female)

     total_bill   tip     sex smoker   day    time  size
198       13.00  2.00  Female    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2

In [115]:
for group in grouped:
    print(group)

    print(type(group[0]))
    print(group[0])

    print(type(group[1]))
    print(group[1])

('Male',      total_bill   tip   sex smoker   day    time  size
24        19.82  3.18  Male     No   Sat  Dinner     2
6          8.77  2.00  Male     No   Sun  Dinner     2
153       24.55  2.00  Male     No   Sun  Dinner     4
211       25.89  5.16  Male    Yes   Sat  Dinner     4
176       17.89  2.00  Male    Yes   Sun  Dinner     2
192       28.44  2.56  Male    Yes  Thur   Lunch     2
9         14.78  3.23  Male     No   Sun  Dinner     2)
<class 'str'>
Male
<class 'pandas.core.frame.DataFrame'>
     total_bill   tip   sex smoker   day    time  size
24        19.82  3.18  Male     No   Sat  Dinner     2
6          8.77  2.00  Male     No   Sun  Dinner     2
153       24.55  2.00  Male     No   Sun  Dinner     4
211       25.89  5.16  Male    Yes   Sat  Dinner     4
176       17.89  2.00  Male    Yes   Sun  Dinner     2
192       28.44  2.56  Male    Yes  Thur   Lunch     2
9         14.78  3.23  Male     No   Sun  Dinner     2
('Female',      total_bill   tip     sex smoker   day    time  size
198       13.00  2.00  Female    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2)
<class 'str'>
Female
<class 'pandas.core.frame.DataFrame'>
     total_bill   tip     sex smoker   day    time  size
198       13.00  2.00  Female    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2

In [124]:
bill_sex_time = tips_10.groupby(['sex', 'time'])
print(bill_sex_time)
group_avg = bill_sex_time.mean(numeric_only=True)

print(type(group_avg))
print(group_avg)
print(group_avg.index)
print(group_avg.reset_index())

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002517EF992E0>
<class 'pandas.core.frame.DataFrame'>
               total_bill       tip      size
sex    time
Male   Lunch    28.440000  2.560000  2.000000
       Dinner   18.616667  2.928333  2.666667
Female Lunch    12.740000  2.260000  2.000000
       Dinner   15.380000  3.000000  2.000000
MultiIndex([(  'Male',  'Lunch'),
            (  'Male', 'Dinner'),
            ('Female',  'Lunch'),
            ('Female', 'Dinner')],
           names=['sex', 'time'])
      sex    time  total_bill       tip      size
0    Male   Lunch   28.440000  2.560000  2.000000
1    Male  Dinner   18.616667  2.928333  2.666667
2  Female   Lunch   12.740000  2.260000  2.000000
3  Female  Dinner   15.380000  3.000000  2.000000

C:\Users\taehy\AppData\Local\Temp\ipykernel_24088\1099729757.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bill_sex_time = tips_10.groupby(['sex', 'time'])

In [147]:
# normal index
df = pd.DataFrame({
    'id' : [10, 10, 20],
    'name' : ['Jake', 'Mike', 'June'],
    'age' : [33, 35, 30]
    })

df1 = df.set_index('id')

print(df1)
print(df1.loc[20])

    name  age
id
10  Jake   33
10  Mike   35
20  June   30
name    June
age       30
Name: 20, dtype: object

In [154]:
df2 = df.set_index(['id', 'name'])
print(df2)
print(df2.loc[10])
print(df2.loc[(10, 'Mike')])

         age
id name
10 Jake   33
   Mike   35
20 June   30
      age
name
Jake   33
Mike   35
age    35
Name: (10, Mike), dtype: int64