In [139]:
import pandas as pd

CCTV_Seoul = pd.read_csv('seoul_cctv_b2011_2018.csv', encoding='euc-kr')
CCTV_Seoul.head()

     기관명    소계  2011년이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강 남 구  5221   1944.0  195.0  316.0    430    546    765    577    448
1  강 동 구  1879    303.0  387.0  134.0     59    144    194    273    385
2  강 북 구  1265    243.0   88.0  141.0     74    145    254      1    319
3  강 서 구  1617    219.0  155.0  118.0    230    187    190    264    254
4  관 악 구  3985    430.0   56.0  419.0    487    609    619    694    671

In [140]:
CCTV_Seoul.columns
CCTV_Seoul.columns[0]

'기관명'

In [141]:

CCTV_Seoul.rename(columns={CCTV_Seoul.columns[0] : '구별'}, inplace=True)

In [142]:
CCTV_Seoul.head()

      구별    소계  2011년이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강 남 구  5221   1944.0  195.0  316.0    430    546    765    577    448
1  강 동 구  1879    303.0  387.0  134.0     59    144    194    273    385
2  강 북 구  1265    243.0   88.0  141.0     74    145    254      1    319
3  강 서 구  1617    219.0  155.0  118.0    230    187    190    264    254
4  관 악 구  3985    430.0   56.0  419.0    487    609    619    694    671

In [143]:
pop_Seoul = pd.read_excel('01. population_in_Seoul.xls')
pop_Seoul.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
0,기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자
1,기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2,2017.1/4,합계,4202888,10197604,5000005,5197599,9926968,4871560,5055408,270636,128445,142191,2.36,1321458
3,2017.1/4,종로구,72654,162820,79675,83145,153589,75611,77978,9231,4064,5167,2.11,25425
4,2017.1/4,중구,59481,133240,65790,67450,124312,61656,62656,8928,4134,4794,2.09,20764

In [144]:
pop_Seoul = pd.read_excel('01. population_in_Seoul.xls',
                          header = 2,
                          usecols="B, D, G, J, N")
pop_Seoul.head()

   자치구           계        계.1       계.2   65세이상고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [145]:
pop_Seoul.rename(columns= {pop_Seoul.columns[0] : '구별',
                           pop_Seoul.columns[1] : '인구수',
                           pop_Seoul.columns[2] : '한국인',
                           pop_Seoul.columns[3] : '외국인',
                           pop_Seoul.columns[4] : '고령자'}, inplace=True)
pop_Seoul.head()

    구별         인구수        한국인       외국인        고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [146]:
import pandas as pd
import numpy as np

s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [147]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [148]:
np.random.randn(6, 4)

array([[-1.8326829 , -0.48379483,  1.50821546, -0.27248409],
       [-0.55988634,  0.96581209, -1.53428666,  0.99351368],
       [-1.41849194,  0.77946887,  0.73049517,  0.58517609],
       [-0.89983666,  0.68711959, -2.08689133, -0.69683582],
       [-0.24035545,  0.43509853, -0.43106685, -0.83060129],
       [-1.90175709,  0.16330247, -1.1835718 ,  0.68794248]])

In [149]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['A', 'B', 'C', 'D'])
df.head(3)

                   A         B         C         D
2013-01-01  0.514963  0.102890  0.703357  1.124364
2013-01-02  0.138115  0.346869  0.426341  0.428730
2013-01-03  0.383372 -0.633898  0.068670 -0.118849

In [150]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [151]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [152]:
df.values

array([[ 0.51496299,  0.10288976,  0.70335666,  1.12436446],
       [ 0.13811506,  0.34686855,  0.42634091,  0.42873037],
       [ 0.38337186, -0.63389786,  0.06867048, -0.11884904],
       [-0.55059771, -0.29449312, -1.26544659, -0.22615682],
       [-0.03003041, -0.92376402, -0.64297413,  0.70598286],
       [ 0.98234389, -0.54415833, -0.37186931,  0.82532351]])

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2013-01-01 to 2013-01-06
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes

In [154]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.239694 -0.324426 -0.180320  0.456566
std    0.520687  0.476947  0.726520  0.537054
min   -0.550598 -0.923764 -1.265447 -0.226157
25%    0.012006 -0.611463 -0.575198  0.018046
50%    0.260743 -0.419326 -0.151599  0.567357
75%    0.482065  0.003544  0.336923  0.795488
max    0.982344  0.346869  0.703357  1.124364

In [155]:
df.sort_values(by="C", ascending=True)

                   A         B         C         D
2013-01-04 -0.550598 -0.294493 -1.265447 -0.226157
2013-01-05 -0.030030 -0.923764 -0.642974  0.705983
2013-01-06  0.982344 -0.544158 -0.371869  0.825324
2013-01-03  0.383372 -0.633898  0.068670 -0.118849
2013-01-02  0.138115  0.346869  0.426341  0.428730
2013-01-01  0.514963  0.102890  0.703357  1.124364

In [156]:
df["A"]

2013-01-01    0.514963
2013-01-02    0.138115
2013-01-03    0.383372
2013-01-04   -0.550598
2013-01-05   -0.030030
2013-01-06    0.982344
Freq: D, Name: A, dtype: float64

In [157]:
df[0:3]

                   A         B         C         D
2013-01-01  0.514963  0.102890  0.703357  1.124364
2013-01-02  0.138115  0.346869  0.426341  0.428730
2013-01-03  0.383372 -0.633898  0.068670 -0.118849

In [158]:
df["2013-01-01":"2013-01-04"]

                   A         B         C         D
2013-01-01  0.514963  0.102890  0.703357  1.124364
2013-01-02  0.138115  0.346869  0.426341  0.428730
2013-01-03  0.383372 -0.633898  0.068670 -0.118849
2013-01-04 -0.550598 -0.294493 -1.265447 -0.226157

In [159]:
df.loc[dates[0]] # selecting one row

A    0.514963
B    0.102890
C    0.703357
D    1.124364
Name: 2013-01-01 00:00:00, dtype: float64

In [160]:
df.loc[[dates[0], dates[1]]] # multipl rows

                   A         B         C         D
2013-01-01  0.514963  0.102890  0.703357  1.124364
2013-01-02  0.138115  0.346869  0.426341  0.428730

In [161]:
df.loc[["2013-01-01", "2013-01-02"], ["A", "B"]] # Selectign multiple rows and cols

                   A         B
2013-01-01  0.514963  0.102890
2013-01-02  0.138115  0.346869

In [162]:
df.iloc[0]

A    0.514963
B    0.102890
C    0.703357
D    1.124364
Name: 2013-01-01 00:00:00, dtype: float64

In [163]:
df.iloc[0, 0]

np.float64(0.514962988450631)

In [164]:
df.iloc[0:1, [0, 1, 3]]

                   A        B         D
2013-01-01  0.514963  0.10289  1.124364

In [165]:
df2 = df.copy()
df2['E'] = [1, 2, 3, 4, 5, 6]
df2

                   A         B         C         D  E
2013-01-01  0.514963  0.102890  0.703357  1.124364  1
2013-01-02  0.138115  0.346869  0.426341  0.428730  2
2013-01-03  0.383372 -0.633898  0.068670 -0.118849  3
2013-01-04 -0.550598 -0.294493 -1.265447 -0.226157  4
2013-01-05 -0.030030 -0.923764 -0.642974  0.705983  5
2013-01-06  0.982344 -0.544158 -0.371869  0.825324  6

In [166]:
df2['E'].isin([1, 3])

2013-01-01     True
2013-01-02    False
2013-01-03     True
2013-01-04    False
2013-01-05    False
2013-01-06    False
Freq: D, Name: E, dtype: bool

In [167]:
CCTV_Seoul.head()

      구별    소계  2011년이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강 남 구  5221   1944.0  195.0  316.0    430    546    765    577    448
1  강 동 구  1879    303.0  387.0  134.0     59    144    194    273    385
2  강 북 구  1265    243.0   88.0  141.0     74    145    254      1    319
3  강 서 구  1617    219.0  155.0  118.0    230    187    190    264    254
4  관 악 구  3985    430.0   56.0  419.0    487    609    619    694    671

In [168]:
CCTV_Seoul.sort_values(by="소계", ascending=True).head(5)

         구별    소계  2011년이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
9     도 봉 구   858    197.0   66.0    8.0    185     59    155    117     71
24    중 랑 구  1068      NaN    NaN    NaN    770    102    121     66      9
2     강 북 구  1265    243.0   88.0  141.0     74    145    254      1    319
22    종 로 구  1471      8.0    7.0  599.0    132    195    148    281    101
23  중     구  1544     25.0  165.0  114.0     80    245    270    317    328

In [169]:
CCTV_Seoul.sort_values(by="소계", ascending=False).head(5)

       구별    소계  2011년이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0   강 남 구  5221   1944.0  195.0  316.0    430    546    765    577    448
4   관 악 구  3985    430.0   56.0  419.0    487    609    619    694    671
6   구 로 구  3227    852.0  219.0  349.0    187    268    326    540    486
16  성 북 구  3003    779.0   84.0  304.0    241    279    388    285    643
21  은 평 구  2962   1365.0   83.0   99.0    343    180    296    229    367

In [170]:
CCTV_Seoul["최근증가율"] = (CCTV_Seoul["2012년"] + CCTV_Seoul["2013년"] + CCTV_Seoul["2014년"] + CCTV_Seoul["2015년"] + CCTV_Seoul["2016년"] + CCTV_Seoul["2017년"] + CCTV_Seoul["2018년"]) / CCTV_Seoul["2011년이전"]
CCTV_Seoul.sort_values(by="최근증가율", ascending=False).head(10)

,구별,소계,2011년이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,최근증가율
22,종 로 구,1471,8.0,7.0,599.0,132,195,148,281,101,182.875000
23,중 구,1544,25.0,165.0,114.0,80,245,270,317,328,60.760000
7,금 천 구,1634,27.0,17.0,242.0,101,382,136,199,530,59.518519
19,영등포구,2495,132.0,121.0,206.0,217,366,289,371,793,17.901515
4,관 악 구,3985,430.0,56.0,419.0,487,609,619,694,671,8.267442
11,동 작 구,1780,238.0,93.0,29.0,503,130,254,278,255,6.478992
3,강 서 구,1617,219.0,155.0,118.0,230,187,190,264,254,6.383562
1,강 동 구,1879,303.0,387.0,134.0,59,144,194,273,385,5.201320
2,강 북 구,1265,243.0,88.0,141.0,74,145,254,1,319,4.205761
9,도 봉 구,858,197.0,66.0,8.0,185,59,155,117,71,3.355330

In [171]:
pop_Seoul.head(10)

     구별         인구수        한국인       외국인        고령자
0    합계  10197604.0  9926968.0  270636.0  1321458.0
1   종로구    162820.0   153589.0    9231.0    25425.0
2    중구    133240.0   124312.0    8928.0    20764.0
3   용산구    244203.0   229456.0   14747.0    36231.0
4   성동구    311244.0   303380.0    7864.0    39997.0
5   광진구    372164.0   357211.0   14953.0    42214.0
6  동대문구    369496.0   354079.0   15417.0    54173.0
7   중랑구    414503.0   409882.0    4621.0    56774.0
8   성북구    461260.0   449773.0   11487.0    64692.0
9   강북구    330192.0   326686.0    3506.0    54813.0

In [172]:
pop_Seoul.drop([0], inplace=True)
pop_Seoul.head(10)

      구별       인구수       한국인      외국인      고령자
1    종로구  162820.0  153589.0   9231.0  25425.0
2     중구  133240.0  124312.0   8928.0  20764.0
3    용산구  244203.0  229456.0  14747.0  36231.0
4    성동구  311244.0  303380.0   7864.0  39997.0
5    광진구  372164.0  357211.0  14953.0  42214.0
6   동대문구  369496.0  354079.0  15417.0  54173.0
7    중랑구  414503.0  409882.0   4621.0  56774.0
8    성북구  461260.0  449773.0  11487.0  64692.0
9    강북구  330192.0  326686.0   3506.0  54813.0
10   도봉구  348646.0  346629.0   2017.0  51312.0

In [174]:
pop_Seoul["구별"].unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구', nan],
      dtype=object)

In [188]:
pop_Seoul["구별"].isnull()
pop_Seoul[pop_Seoul["구별"].isnull()]

     구별  인구수  한국인  외국인  고령자
26  NaN  NaN  NaN  NaN  NaN

In [ ]:
pop_Seoul.drop([26], inplace=True)