In [46]:
import numpy as np
import pandas as pd

raw_crime_anal_police = pd.read_csv("2015_crime_in_seoul.csv", thousands=',', encoding='euc-kr').dropna()

raw_crime_anal_police

     구분  죄종 발생검거      건수
0    중부  살인   발생     2.0
1    중부  살인   검거     2.0
2    중부  강도   발생     3.0
3    중부  강도   검거     2.0
4    중부  강간   발생   105.0
..   ..  ..  ...     ...
305  수서  강간   검거   124.0
306  수서  절도   발생  1439.0
307  수서  절도   검거   666.0
308  수서  폭력   발생  1819.0
309  수서  폭력   검거  1559.0

[310 rows x 4 columns]

In [68]:
crime_anal_police = pd.DataFrame(columns=["살인발생", "살인검거", "강도발생", "강도검거", "강간발생", "강간검거", "절도발생", "절도검거", "폭력발생", "폭력검거"], index= raw_crime_anal_police["구분"].unique())

crime_anal_police.head(10)

    살인발생 살인검거 강도발생 강도검거 강간발생 강간검거 절도발생 절도검거 폭력발생 폭력검거
중부   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
종로   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
남대문  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
서대문  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
혜화   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
용산   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
성북   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
동대문  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
마포   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
영등포  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [69]:
print(raw_crime_anal_police["죄종"][0])
for idx, row in raw_crime_anal_police.iterrows():
    # print(row["구분"], row["죄종"], row["발생검거"], row["건수"])
    crime = row["죄종"] + row["발생검거"]
    area = row["구분"]
    data = row["건수"]
    if area in crime_anal_police.index and crime in crime_anal_police.columns :
        crime_anal_police.loc[area, crime] = data

crime_anal_police.head(10)

살인

     살인발생  살인검거  강도발생  강도검거   강간발생   강간검거    절도발생   절도검거    폭력발생    폭력검거
중부    2.0   2.0   3.0   2.0  105.0   65.0  1395.0  477.0  1355.0  1170.0
종로    3.0   3.0   6.0   5.0  115.0   98.0  1070.0  413.0  1278.0  1070.0
남대문   1.0   0.0   6.0   4.0   65.0   46.0  1153.0  382.0   869.0   794.0
서대문   2.0   2.0   5.0   4.0  154.0  124.0  1812.0  738.0  2056.0  1711.0
혜화    3.0   2.0   5.0   4.0   96.0   63.0  1114.0  424.0  1015.0   861.0
용산    5.0   5.0  14.0  14.0  194.0  173.0  1557.0  587.0  2050.0  1704.0
성북    2.0   2.0   2.0   1.0   86.0   71.0   953.0  409.0  1194.0  1015.0
동대문   5.0   5.0  13.0  13.0  173.0  146.0  1981.0  814.0  2548.0  2227.0
마포    8.0   8.0  14.0  10.0  294.0  247.0  2555.0  813.0  2983.0  2519.0
영등포  14.0  12.0  22.0  20.0  295.0  183.0  2964.0  978.0  3572.0  2961.0

In [70]:
crime_anal_police.index = "서울" + crime_anal_police.index + "경찰서" 
crime_anal_police.head()

         살인발생 살인검거 강도발생 강도검거   강간발생   강간검거    절도발생   절도검거    폭력발생    폭력검거
서울중부경찰서   2.0  2.0  3.0  2.0  105.0   65.0  1395.0  477.0  1355.0  1170.0
서울종로경찰서   3.0  3.0  6.0  5.0  115.0   98.0  1070.0  413.0  1278.0  1070.0
서울남대문경찰서  1.0  0.0  6.0  4.0   65.0   46.0  1153.0  382.0   869.0   794.0
서울서대문경찰서  2.0  2.0  5.0  4.0  154.0  124.0  1812.0  738.0  2056.0  1711.0
서울혜화경찰서   3.0  2.0  5.0  4.0   96.0   63.0  1114.0  424.0  1015.0   861.0

In [76]:
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="my_app")
location = geolocator.geocode("서울중부경찰서")

print(location.address)
print(location.latitude, location.longitude)

서울중부경찰서, 수표로, 저동2가, 을지로동, 중구, 서울특별시, 04552, 대한민국
37.5635877 126.9895776

In [95]:
from geopy.geocoders import Nominatim
import time

locations = {}
geolocator = Nominatim(user_agent="my_app_1234")
for name in crime_anal_police.index:
    location = geolocator.geocode(name)
    if location :
        time.sleep(2)
        print(location.address)
        locations[name] = location.address

서울중부경찰서, 수표로, 저동2가, 을지로동, 중구, 서울특별시, 04552, 대한민국
서울종로경찰서, 율곡로, 종로2가, 관훈동, 종로1·2·3·4가동, 종로구, 서울특별시, 03146, 대한민국
서울남대문경찰서, 410, 한강대로, 남대문로5가, 회현동, 중구, 서울특별시, 04637, 대한민국
서울서대문경찰서 신촌지구대, 이화여대7길, 대현동, 신촌동, 서대문구, 서울특별시, 03766, 대한민국
동묘앞.서울혜화경찰서(중), 종로, 숭인2동, 종로구, 서울특별시, 03115, 대한민국
서울동대문경찰서, 29, 약령시로21길, 청량리동, 동대문구, 서울특별시, 02486, 대한민국
서울마포경찰서 홍익지구대, 양화로11길, 서교동, 마포구, 서울특별시, 04035, 대한민국
서울영등포경찰서 여의도지구대, 120, 여의공원로, 여의도동, 여의동, 영등포구, 서울특별시, 07243, 대한민국
서울금천경찰서, 50, 시흥대로73길, 시흥1동, 금천구, 서울특별시, 08611, 대한민국
서울중랑경찰서, 신내역로3길, 신내1동, 중랑구, 서울특별시, 02056, 대한민국
서울강남경찰서, 11, 테헤란로114길, 대치동, 대치2동, 강남구, 서울특별시, 06175, 대한민국
서울관악경찰서, 관악로5길, 갑을아파트, 청룡동, 관악구, 서울특별시, 08791, 대한민국
서울강서경찰서, 방화동로, 공항동, 강서구, 서울특별시, 07619, 대한민국
서울강동경찰서, 성내로13길, 성내동, 성내1동, 강동구, 서울특별시, 05396, 대한민국
서울양천경찰서 교통정보센터, 192, 목동서로, 목1동, 양천구, 서울특별시, 07992, 대한민국
거여파출소, 위례서로, 위례신도시, 위례동, 송파구, 서울특별시, 05790, 대한민국
서울은평경찰서, 365, 연서로, 불광2동, 은평구, 서울특별시, 03338, 대한민국
서울수서경찰서, 617, 개포로, 개포3동, 강남구, 서울특별시, 06336, 대한민국

In [91]:
full_address = "서울중부경찰서, 수표로, 저동2가, 을지로동, 중구, 서울특별시, 04552, 대한민국"
area = [item.strip() for item in full_address.split(',') if item.strip()[-1] == "구"]
area

['중구']

In [85]:
full_address = "서울중부경찰서, 수표로, 저동2가, 을지로동, 중구, 서울특별시, 04552, 대한민국"
area = [item.strip() for item in full_address.split(',') if item.strip()[-1] == "구"]

In [102]:
for police in crime_anal_police.index:
    full_address = locations.get(police, None)
    area = None
    if full_address:
        area = next(item.strip() for item in full_address.split(',') if item.strip()[-1] == "구")
        if area : 
            crime_anal_police.loc[police, "구역"] = area

crime_anal_police

,살인발생,살인검거,강도발생,강도검거,강간발생,강간검거,절도발생,절도검거,폭력발생,폭력검거,구역
서울중부경찰서,2.0,2.0,3.0,2.0,105.0,65.0,1395.0,477.0,1355.0,1170.0,중구
서울종로경찰서,3.0,3.0,6.0,5.0,115.0,98.0,1070.0,413.0,1278.0,1070.0,종로구
서울남대문경찰서,1.0,0.0,6.0,4.0,65.0,46.0,1153.0,382.0,869.0,794.0,중구
서울서대문경찰서,2.0,2.0,5.0,4.0,154.0,124.0,1812.0,738.0,2056.0,1711.0,서대문구
서울혜화경찰서,3.0,2.0,5.0,4.0,96.0,63.0,1114.0,424.0,1015.0,861.0,종로구
서울용산경찰서,5.0,5.0,14.0,14.0,194.0,173.0,1557.0,587.0,2050.0,1704.0,na
서울성북경찰서,2.0,2.0,2.0,1.0,86.0,71.0,953.0,409.0,1194.0,1015.0,na
서울동대문경찰서,5.0,5.0,13.0,13.0,173.0,146.0,1981.0,814.0,2548.0,2227.0,동대문구
서울마포경찰서,8.0,8.0,14.0,10.0,294.0,247.0,2555.0,813.0,2983.0,2519.0,마포구
서울영등포경찰서,14.0,12.0,22.0,20.0,295.0,183.0,2964.0,978.0,3572.0,2961.0,영등포구
서울성동경찰서,4.0,4.0,9.0,8.0,126.0,119.0,1607.0,597.0,1612.0,1395.0,na
서울동작경찰서,5.0,5.0,9.0,5.0,285.0,139.0,1865.0,661.0,1910.0,1587.0,na
서울광진경찰서,4.0,4.0,14.0,26.0,240.0,220.0,3026.0,1277.0,2625.0,2180.0,na
서울서부경찰서,2.0,2.0,2.0,1.0,70.0,59.0,819.0,293.0,1192.0,1038.0,na
서울강북경찰서,7.0,8.0,14.0,13.0,153.0,126.0,1434.0,618.0,2649.0,2348.0,na
서울금천경찰서,3.0,4.0,6.0,6.0,151.0,122.0,1567.0,888.0,2054.0,1776.0,금천구
서울중랑경찰서,13.0,12.0,11.0,9.0,187.0,148.0,2135.0,829.0,2847.0,2407.0,중랑구
서울강남경찰서,3.0,3.0,15.0,12.0,300.0,225.0,2411.0,984.0,2465.0,2146.0,강남구
서울관악경찰서,9.0,8.0,12.0,14.0,320.0,221.0,2706.0,827.0,3298.0,2642.0,관악구
서울강서경찰서,7.0,8.0,13.0,13.0,262.0,191.0,2096.0,1260.0,3207.0,2718.0,강서구
서울강동경찰서,4.0,3.0,6.0,8.0,156.0,123.0,2366.0,789.0,2712.0,2248.0,강동구
서울종암경찰서,3.0,3.0,3.0,3.0,64.0,53.0,832.0,332.0,1015.0,840.0,na
서울구로경찰서,8.0,6.0,15.0,11.0,281.0,164.0,2335.0,889.0,3007.0,2432.0,na
서울서초경찰서,7.0,4.0,8.0,5.0,334.0,193.0,1982.0,905.0,1852.0,1607.0,na
서울양천경찰서,3.0,5.0,6.0,3.0,120.0,105.0,1890.0,672.0,2509.0,2030.0,양천구
서울송파경찰서,11.0,10.0,13.0,10.0,220.0,178.0,3239.0,1129.0,3295.0,2786.0,송파구
서울노원경찰서,10.0,10.0,7.0,7.0,197.0,121.0,2193.0,801.0,2723.0,2329.0,na
서울방배경찰서,1.0,2.0,1.0,1.0,59.0,56.0,653.0,186.0,547.0,491.0,na
서울은평경찰서,1.0,1.0,7.0,5.0,96.0,82.0,1095.0,418.0,1461.0,1268.0,은평구
서울도봉경찰서,3.0,3.0,9.0,10.0,102.0,106.0,1063.0,478.0,1487.0,1303.0,na
서울수서경찰서,10.0,7.0,6.0,6.0,149.0,124.0,1439.0,666.0,1819.0,1559.0,강남구

In [ ]:
result = crime_anal_police.index[crime_anal_police["구역"] == "na"]
print(result)

crime

Index(['서울용산경찰서', '서울성북경찰서', '서울성동경찰서', '서울동작경찰서', '서울광진경찰서', '서울서부경찰서',
       '서울강북경찰서', '서울종암경찰서', '서울구로경찰서', '서울서초경찰서', '서울노원경찰서', '서울방배경찰서',
       '서울도봉경찰서'],
      dtype='object')

In [110]:
crime_anal_police.loc["서울용산경찰서", "구역"] = "용산구"
crime_anal_police.loc["서울성북경찰서", "구역"] = "성북구"
crime_anal_police.loc["서울성동경찰서", "구역"] = "성동구"
crime_anal_police.loc["서울동작경찰서", "구역"] = "광진구"
crime_anal_police.loc["서울서부경찰서", "구역"] = "은평구"
crime_anal_police.loc["서울강북경찰서", "구역"] = "강북구"
crime_anal_police.loc["서울종암경찰서", "구역"] = "성북구"
crime_anal_police.loc["서울구로경찰서", "구역"] = "구로구"
crime_anal_police.loc["서울서초경찰서", "구역"] = "서초구"
crime_anal_police.loc["서울노원경찰서", "구역"] = "노원구"
crime_anal_police.loc["서울방배경찰서", "구역"] = "서초구"
crime_anal_police.loc["서울도봉경찰서", "구역"] = "도봉구"
crime_anal_police.loc["서울광진경찰서", "구역"] = "광진구"

In [111]:
crime_anal_police.to_csv("2015_crime_in_seoul_processed.csv", sep=",", encoding="utf-8")